version: 2.1

executors:
  node12:
    working_directory: /home/circleci/nmsys
    docker:
      - image: cimg/node:12.16
    environment:
      CI: "true"
      ENV: "ci"
      APP: /home/circleci/nmsys
      CACHE: /tmp/caches

commands:
  info:
    description: Start workflow
    steps:
      - hello/circleci-env-highlights
      - hello/system-info

orbs:
  hello: circleci/hello-build@0.0.14
  codecov: codecov/codecov@1.0.5
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  main:
    executor: node12
    steps:
      - checkout
      - info
      - restore_cache:
          keys:
            - v1-lerna-{{ checksum "yarn.lock" }}
            - v1-lerna-
      - run:
          name: Installing... root dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Bootstraping... lerna dependencies
          command: yarn bootstrap
      - save_cache:
          paths:
            - node_modules
            - /home/circleci/.yarn
            - /home/circleci/.cache
          key: v1-lerna-{{ checksum "yarn.lock" }}
      - run:
          name: Building...
          command: yarn build:ci
      - run:
          name: Testing...
          command: yarn test:ci

workflows:
  version: 2
  default:
    jobs:
      - main
