version: 2.1

orbs:
  hello: circleci/hello-build@0.0.14
  node: circleci/node@2.1.0
  codecov: codecov/codecov@1.0.5
  sonarcloud: sonarsource/sonarcloud@1.0.1

commands:
  info:
    description: Start workflow
    steps:
      - hello/circleci-env-highlights
      - hello/system-info
  gpg-setup:
    description: GPG setup
    steps:
      - run:
          name: Import private key to gpg
          command: echo "$GPG_PRIVATE_KEY_BASE64" | base64 --decode | gpg --batch --allow-secret-key-import --import
      - run:
          name: Checking keys in gpg
          command: gpg --keyid-format LONG --list-secret-keys
  gpg-cleanup:
    description: GPG cleanup
    steps:
      - run:
          name: Delete gpg private key
          command: gpg --batch --yes --delete-secret-key "$GPG_IDENTIFY_KEY"
      - run:
          name: Delete gpg public key
          command: gpg --batch --yes --delete-key "$GPG_IDENTIFY_KEY"
      - run:
          name: Checking keys in gpg
          command: gpg --keyid-format LONG --list-secret-key
  git-setup:
    description: Git setup
    steps:
      - run:
          name: Add git user email
          command: git config --global user.email "ci@kamontat.net"
      - run:
          name: Add git username
          command: git config --global user.name "Kamontat Chantrachirathumrong [bot]"
      - run:
          name: Add git sign key
          command: git config --global user.signingKey "$GPG_SIGNING_KEY"

jobs:
  main:
    docker:
      - image: "cimg/node:12.16"
    environment:
      ENV: "ci"
      JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
    steps:
      - add_ssh_keys:
          name: github.com
          fingerprints:
            - "95:d8:61:2a:85:ad:42:2d:08:80:de:bb:1b:96:c9:13"
      - checkout
      - info
      - gpg-setup
      - git-setup
      - node/install-packages:
          cache-version: "v1-lerna"
          cache-key: "yarn.lock"
          pkg-manager: yarn
          include-branch-in-cache-key: false
      - run:
          name: Bootstraping...
          command: yarn bootstrap
      - run:
          name: Building...
          command: yarn build:ci
      - run:
          name: Testing...
          command: yarn test:ci
      - run:
          name: Dumping version...
          command: yarn version:ci || true
      - run:
          name: Releasing...
          command: yarn release:ci || true
      - gpg-cleanup
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./coverage
          destination: reports/coverage
      - store_artifacts:
          path: ./reports/junit/
          destination: reports/junit

workflows:
  version: 2
  default:
    jobs:
      - main
